<?php

/**
 * Implement hook_form()
 */
function game_form($node, $form_state) {
    return node_content_form($node, $form_state);
}


/**
 * Implements hook_node_info()
 */
function gamecontenttype_node_info() {
    return array(
        'game' => array(
            'name' => t('Game'),
            'base' => 'game',
            'description' => t('Contains game information'),
            'has_title' => FALSE,
            'title_label' => t('Product title')
         )
    );
}




